# Set the project language
language: python

# Set up the build matrix
# TODO: Would be nice to add other supported Python versions in here, but the
# rootpy project doesn't currently provide ROOT builds for CI testing, and I'm
# far too lazy to do that myself
python:
  - "2.7"
  - "3.4"
env:
  - ROOT=5.34.18

# Install testing dependencies and the module itself
# NOTE: We use the ROOT build provided by root_numpy:
# https://github.com/rootpy/root_numpy/blob/master/ci/install.sh
install:
  - wget --no-check-certificate https://copy.com/rtIyUdxgjt7h/ci/root_builds/ROOT-${ROOT}_Python-${TRAVIS_PYTHON_VERSION}_GCC-4.8_x86_64.tar.gz
  - tar zxf ROOT-${ROOT}_Python-${TRAVIS_PYTHON_VERSION}_GCC-4.8_x86_64.tar.gz
  - mv ROOT-${ROOT}_Python-${TRAVIS_PYTHON_VERSION}_GCC-4.8_x86_64 root
  - source root/bin/thisroot.sh
  - pip install pep8
  - pip install git+https://github.com/havoc-io/owls-cache.git
  - pip install git+https://github.com/havoc-io/owls-parallel.git
  - pip install -e .

# Run PEP-8 compliance testing and unit tests
script:
  - common/scripts/run-pep8.sh
  - common/scripts/run-tests.sh

# Send notifications
notifications:
  email:
    - jacob@havoc.io
